### ISSUE TITLE
SymbolicUtils v1 upgrade

### ISSUE THREAD

**Issue by YingboMa** [ai4energy/Ai4EComponentLib.jl#45]
SymbolicUtils v1 is a breaking release. Please follow https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/page/upgrade.md to upgrade.

**Comment by jake484** [comment]
Update @register to @register_symbolic, I think that's all. Please let me know if need to update something else.

**Comment by YingboMa** [comment]
Can you enable the CI to run the tests?

**Comment by jake484** [comment]
done.

**Comment by YingboMa** [comment]
Great, thanks!
